# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

  platform :ios, '15.5'
  IOS_VERSION = '15.5'

  inhibit_all_warnings!
  prepare_react_native_project!

  linkage = ENV['USE_FRAMEWORKS']

  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end
   config = use_native_modules!

target 'SmartWorkForce' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    hermes_enabled: true,
    fabric_enabled: true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
  
    
  target 'SmartWorkForceTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name == 'React-Core-AccessibilityResources'
        def pod.resource_bundle_targets
          []
        end
      end
    end
  end
  

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Add the following
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end
